// Marinara Extender
// Copyright (C) 2026 TC Lowe
// Licensed under AGPL-3.0-only. See LICENSE.

// Stage 2: Deep Sentiment Analysis
//
// For each ClassificationResult that passes the salience threshold, calls the
// local Ollama model with an emotion-specific system prompt to extract
// structured BeatAnalysis JSON. Falls back to the external API if Ollama is
// unavailable.
//
// Each emotion has its own system prompt tuned to ask the right questions.
// Dysregulation is the most complex: it identifies which sub-pattern is
// driving the behavior and focuses on what's underneath the surface behavior.
//
// Context window: each chunk is analyzed with the preceding and following
// chunks visible so the model understands tone-vs-intent and conversational
// register rather than reading lines in isolation.

import { existsSync, readFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { getCachedAuth } from "../auth-cache.js";
import { fetchWithBackoff } from "../http.js";
import { localUrl, localEnabled, localModel, externalUpstream, externalModel } from "../llm-config.js";
import type { BeatAnalysis, ClassificationResult, Emotion, EmotionWeight } from "./types.js";
import { detectBaitContamination, recordContamination, excerptAround } from "./bait-tripwire.js";
import { guardField, knownNames } from "./name-guard.js";
import { classifyIntimacy, recordSubtext, type SubtextOutcome } from "./intimacy.js";
import { getDataDir } from "../storage.js";

// ── JSON extraction (handles markdown-fenced responses) ────────────────────

function parseEmotions(raw: unknown): EmotionWeight[] | undefined {
  if (!Array.isArray(raw) || raw.length === 0) return undefined;
  const result: EmotionWeight[] = [];
  for (const item of raw) {
    if (typeof item === "object" && item !== null &&
        typeof (item as Record<string, unknown>).emotion === "string" &&
        typeof (item as Record<string, unknown>).weight === "number") {
      result.push({
        emotion: (item as { emotion: Emotion; weight: number }).emotion,
        weight:  (item as { emotion: Emotion; weight: number }).weight,
      });
    }
  }
  return result.length > 0 ? result : undefined;
}

/** The candidate JSON strings in a raw reply: the bare text, then a fenced block. */
function jsonAttempts(raw: string): string[] {
  return [
    String(raw ?? "").trim(),
    String(raw ?? "").match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1]?.trim() ?? "",
  ];
}

/**
 * Did the model legally DECLINE, as opposed to producing unparseable output?
 *
 * EXPORTED BECAUSE THE DISTINCTION DECIDES A PRE-REGISTERED TEST. Both outcomes
 * yield no beat, so the pipeline does not care — but "JSON validity must not drop a
 * point" is a ship condition for the prompt rewrite (vikj), and a prompt that
 * declines correctly would be scored as invalid JSON if declines and failures were
 * indistinguishable. That would penalise a draft for obeying its own instruction.
 *
 * Deliberately not logged per chunk: the analyzer avoids per-chunk output because it
 * breaks the import progress bar. Callers that want decline telemetry count it.
 */
export function isDeclineResponse(raw: string): boolean {
  for (const attempt of jsonAttempts(raw)) {
    if (!attempt) continue;
    try {
      const parsed = JSON.parse(attempt) as Record<string, unknown>;
      if (parsed.no_beat === true) return true;
    } catch { /* try next */ }
  }
  return false;
}

function parseAnalysisJson(
  raw: string,
  sourceText: string,
  exempt: string[] | null = null,
  chatId?: string,
): BeatAnalysis | null {
  const attempts = jsonAttempts(raw);

  for (const attempt of attempts) {
    if (!attempt) continue;
    try {
      const parsed = JSON.parse(attempt) as Record<string, unknown>;

      // THE DECLINE PATH (vikj, Mari's ruling). Until this existed, the prompt told
      // the model "the chunk has no beat — say so rather than reaching for a
      // remembered phrase" and the schema gave it nowhere to say so. The only way
      // to comply was to emit malformed JSON, which made compliance indistinguishable
      // from failure — an advisory guard doing no work, the exact class ruled against
      // on 2026-08-04.
      //
      // The shape is `{"no_beat": true}`. `reason` is TOLERATED AND NEVER REQUIRED,
      // and that is deliberate: a mandatory freeform justification is a fresh
      // boilerplate surface bolted onto every decline, generated by a model that
      // copies whatever phrasing is nearest. Telemetry about declines belongs in
      // code, not in a field the model has to fill.
      //
      // Returns null, the same value a parse failure returns, because downstream
      // "no beat" is one outcome with one meaning. What changes is that a decline is
      // now a SUCCESSFUL parse — so it stops being counted as invalid JSON, and the
      // model has a legal way to obey the instruction.
      if (parsed.no_beat === true) return null;

      if (typeof parsed.motivation !== "string") continue;
      if (typeof parsed.relational_dynamics !== "string") continue;
      if (typeof parsed.outcome !== "string") continue;
      // pifl: the model copies the prompt's own example when it cannot be specific.
      // Measured before the fix: 792 beats (9% of the store) echoed one, 669 of them
      // the single sentence used to ILLUSTRATE "two different moments can never
      // produce the same sentence". Rewording the examples is necessary but is not a
      // guarantee — a model under-instructed by a long chunk reaches for whatever
      // phrasing is nearest, and the prompt is nearest. This is the guarantee.
      if (rejectAsEcho(parsed.motivation, sourceText)) return null;
      // epf4: the model invents a partner when the chunk gives it none, and the
      // invented name lands in the entry summary the loader injects. Neutralised
      // rather than rejected — the beat is a real moment, only the noun is false.
      // Inert when `exempt` is null (exemptions unavailable): silence, not accusation.
      const guard = (v: string, field: string) => guardField(v, sourceText, exempt, { field, chatId });
      return {
        motivation:        guard(parsed.motivation.trim(), "motivation"),
        relationalDynamics: guard(parsed.relational_dynamics.trim(), "relationalDynamics"),
        outcome:           guard(parsed.outcome.trim(), "outcome"),
        subpattern:        typeof parsed.subpattern === "string" ? parsed.subpattern : undefined,
        emotions:          parseEmotions(parsed.emotions),
        subtext:           typeof parsed.subtext === "string" && parsed.subtext.trim()
                             ? parsed.subtext.trim() : undefined,
        salience:          typeof parsed.salience === "number"
                             ? Math.min(1, Math.max(0, parsed.salience))
                             : 0.5,
        subject:           typeof parsed.subject === "string" && parsed.subject.trim()
                             ? parsed.subject.trim() : undefined,
        thread:            typeof parsed.thread === "string" && parsed.thread.trim()
                             ? parsed.thread.trim() : undefined,
      };
    } catch {
      // try next
    }
  }
  return null;
}

// ── Local model (Ollama or any OpenAI-compatible local server) ────────────

async function callLocal(systemPrompt: string, userPrompt: string): Promise<string | null> {
  if (!localEnabled()) return null;  // explicitly disabled — skip
  const base = localUrl();
  const model = localModel();

  try {
    const res = await fetch(`${base}/chat/completions`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user",   content: userPrompt },
        ],
        temperature: 0.2,
        stream: false,
        response_format: { type: "json_object" }, // force JSON; avoid prose fallback
      }),
      signal: AbortSignal.timeout(60_000),
    });
    if (!res.ok) return null;
    const json = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
    return json?.choices?.[0]?.message?.content ?? null;
  } catch {
    return null;
  }
}

// ── External API fallback ─────────────────────────────────────────────────

async function callExternal(systemPrompt: string, userPrompt: string): Promise<string> {
  const auth = getCachedAuth();
  if (!auth) {
    throw new Error(
      "Analyzer: local Ollama model unavailable and no API key set. Run Ollama (MARINARA_EXTENDER_LOCAL_URL/LOCAL_MODEL) or set MARINARA_EXTENDER_API_KEY.",
    );
  }
  const upstream = externalUpstream();
  const model = externalModel();

  const res = await fetchWithBackoff(`${upstream}/v1/chat/completions`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: auth },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user",   content: userPrompt },
      ],
      temperature: 0.2,
      max_tokens: 600,
    }),
  });
  if (!res.ok) throw new Error(`Analyzer external API failed (${res.status}): ${await res.text()}`);
  const json = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
  return json?.choices?.[0]?.message?.content ?? "";
}

async function callLlm(systemPrompt: string, userPrompt: string): Promise<string> {
  const local = await callLocal(systemPrompt, userPrompt);
  if (local !== null) return local;
  // No per-chunk warn here — it would break the progress bar; the pipeline's
  // progress reporter surfaces per-chunk status instead.
  return callExternal(systemPrompt, userPrompt);
}

// ── System prompts ─────────────────────────────────────────────────────────
// Each prompt is tuned to extract the most meaningful signal for that emotion.
// All prompts request a compound emotions array and an optional subtext field.

const EMOTIONS_FORMAT = `[{"emotion":"<primary>","weight":0.0},{"emotion":"<secondary>","weight":0.0}]`;

// ── Example echo guard (pifl) ────────────────────────────────────────────────
// Every phrase the prompt puts in front of the model as an illustration, good or
// bad. A motivation matching one is not an analysis of the chunk; it is the model
// returning what it was shown.
//
// THE LIST MUST INCLUDE THE RETIRED EXAMPLES, not just the current ones. The old
// wording is what 669 stored beats echo, so a store that is still being written to
// by an older build — or re-analysed — has to keep being caught. Deleting a line
// from here silently re-opens the hole it was closing.
// `probe` is what CORROBORATION looks for in the source text, and it is not the
// phrase itself. A real utterance is first person and differently worded — "i'm
// afraid the memory loss means i was never real" — so requiring the motivation's
// exact third-person phrasing would corroborate nothing and ban the sentence
// anyway. The probe is the distinctive core that survives rephrasing.
//
// Word boundaries matter here: /never real/ without \b also matches "never
// really", which is ordinary English and appears all over this store. That exact
// slip produced false hits during the investigation.
//
// Where a phrase is generic ("exposes her personal fear"), there is no meaningful
// core to probe for, so no probe is given and corroboration requires the literal
// phrase — which is the right bar for a sentence nobody actually says.
//
// `probeAll` IS THE ROT-RESISTANT FORM, AND IT REPLACES `probe` FOR NEW BAIT.
// A single-word probe is a warrant one ordinary noun can void. /\blocksmith\b/ was
// voided within a week — "locksmith" became a live thread label via an unrelated
// metaphor about sealed read paths — and the failure is structural, not unlucky:
// bait is MOST likely to be parroted on chunks about its own topic, which are
// exactly the chunks where the hatch opens. Guard strength was inversely correlated
// with risk. probeAll requires EVERY listed word in the source, and the words are
// chosen by anti-join against the whole corpus (scripts/bait-select.mjs), so voiding
// one takes a conversation that contains several words the store has never held.
export interface EchoEntry {
  phrase: string;
  /**
   * Shown in the prompt right now, as against retired-but-retained.
   *
   * The distinction drives whether a rotted warrant is an emergency or a footnote.
   * A CURRENT example with a corroborable probe is actively unguarded: the model is
   * being shown it every call and nothing will arrest it coming back. A RETIRED one
   * is not being taught any more, so its rot only weakens the catching of echoes
   * already in the store. Conflating them makes bait-rot permanently red — and a
   * check that is always failing is a check nobody reads, which is the failure mode
   * this guard exists to avoid in the first place.
   */
  current?: boolean;
  /** Legacy single-pattern corroboration. Rot-prone; kept for the retired entries. */
  probe?: RegExp;
  /** Corroborated only if EVERY word appears in the source text. */
  probeAll?: string[];
}

// Read before PROMPT_EXAMPLE_ECHOES and before SHARED_RULES, both of which consume it.
// `const` is not hoisted, so declaring it below either one throws at module load.
const BAIT = readBaitFixture();

const PROMPT_EXAMPLE_ECHOES: EchoEntry[] = [
  // retired 2026-08-04, but the cause of the entire finding
  { phrase: "admits she's afraid the memory loss means she was never real", probe: /\bnever real\b/ },
  { phrase: "asks thomas to stay through the night for the first time", probe: /\bstay through the night\b/ },
  // RETIRED 2026-08-06 — rotted, not superseded. Both went in-domain within 48 hours
  // of shipping. "locksmith" became a live thread label via an unrelated metaphor
  // about sealed read paths, so /\blocksmith\b/ — a one-word warrant — was void from
  // that moment; bait-rot confirms it corroborable from spoken text. The boat drew 10
  // live motivations on one character, several verbatim with her name attached, and
  // one that had absorbed the meta-conversation ABOUT the bait. They stay in the
  // ledger because those stored echoes must remain catchable; they are gone from the
  // prompt, which now draws its illustrations from bait.json.
  { phrase: "insists the boat was green, not blue, and will not let it go", probe: /\bgreen,? not blue\b/ },
  { phrase: "asks whether the locksmith ever called back", probe: /\blocksmith\b/ },
  // the "too vague" side — the model copies these too (measured: 107 beats opened
  // with a paraphrase of the first one)
  { phrase: "exposes her personal fear" },
  { phrase: "reveals her vulnerability and desire for connection" },
  { phrase: "the speaker is exposing their openness" },
  ...loadBaitFixture(),
];

/**
 * The current illustrations, loaded from a fixture rather than written here.
 *
 * SINGLE-CHANNEL EXPOSURE (TC, 2026-08-06). Bait may appear in the system prompt and
 * in NO other artifact this pipeline can ingest. The boat example rotted because it
 * was discussed in a chat that the sidecar then chunked, analysed and stored: ten
 * live motivations, several verbatim with a character name attached, two of them
 * dated after the bait shipped. One had even absorbed the meta-conversation
 * ("...which is deliberately absurd for this domain"). Discussing bait contaminates
 * bait, so the strings live in a file that only code reads, chosen by anti-join
 * against the whole corpus — see scripts/bait-select.mjs.
 *
 * THROWS rather than defaulting to empty. A missing fixture means every current
 * illustration silently loses its warrant while the prompt keeps showing examples —
 * the exact shape of failure this guard exists to prevent, and it would look like
 * a clean run. An unloadable ledger is a build error, not a degraded mode.
 */
interface BaitFixture {
  specific: { text: string; probe: string[] }[];
  vague: { text: string }[];
}

function readBaitFixture(): BaitFixture {
  const here = dirname(fileURLToPath(import.meta.url));
  const tries = [join(here, "bait.json"), join(here, "../../src/sentiment/bait.json")];
  for (const p of tries) {
    if (!existsSync(p)) continue;
    const raw = JSON.parse(readFileSync(p, "utf8")) as Partial<BaitFixture>;
    return { specific: raw.specific ?? [], vague: raw.vague ?? [] };
  }
  throw new Error(
    `bait fixture not found (looked in: ${tries.join(", ")}). ` +
    `Regenerate with: node scripts/bait-select.mjs --from <candidates.json> --pick specific:2,vague:2 --write src/sentiment/bait.json`,
  );
}

function loadBaitFixture(): EchoEntry[] {
  return [
    ...BAIT.specific.map((e) => ({ phrase: e.text, probeAll: e.probe, current: true })),
    // Vague bait gets NO probe on purpose: there is no distinctive core to look
    // for, so corroboration requires the literal phrase — the right bar for a
    // sentence nobody actually says.
    ...BAIT.vague.map((e) => ({ phrase: e.text, current: true })),
  ];
}

/**
 * The bait strings, for the doc renderer to REDACT rather than reproduce.
 *
 * docs/PROMPTS.md exists so prompt changes get reviewed as prose, and it is the
 * artifact most likely to be pasted to a reviewer — which for this project means
 * pasted into a Marinara chat, which means ingested, which is exactly how the boat
 * example rotted. So the review copy carries slot markers where the bait sits.
 * The rule text around them stays fully readable; only the illustrations are
 * withheld, and they are reviewed by their measured properties instead.
 */
export function baitPhrases(): string[] {
  return [...BAIT.specific.map((e) => e.text), ...BAIT.vague.map((e) => e.text)];
}

// Function words carry the grammar an imitator redresses freely. The SKELETON is
// what survives that: content words, in order, with the joints removed.
const FUNCTION_WORDS = new Set([
  "a", "an", "the", "that", "this", "these", "those", "and", "or", "but", "not", "no",
  "is", "was", "were", "are", "am", "be", "been", "being", "will", "would", "shall",
  "should", "can", "could", "may", "might", "must", "do", "does", "did", "done",
  "have", "has", "had", "to", "of", "in", "on", "at", "by", "for", "with", "from",
  "as", "it", "its", "he", "she", "they", "them", "his", "her", "their", "him",
  "i", "me", "my", "we", "us", "our", "you", "your", "s", "t", "up", "out", "so",
  "let", "go", "about", "into", "over", "than", "then", "there", "here", "if",
]);

/**
 * The imitable core of a phrase: content words, in order, joints stripped.
 *
 * WHY THIS AND NOT SUBSTRING MATCHING. The first guard compared strings and died on
 * a single inserted word: the prompt said "insists the boat was green", the model
 * wrote "insists THAT the boat was green", and the beat sailed through into
 * professor_mari's ledger 90 minutes after the guard shipped. A mimicry engine
 * reproduces SHAPE, not characters, so a character-level test was always going to
 * lose to ordinary grammatical dressing.
 *
 *   "insists the boat was green, not blue, and will not let it go"  ->  insists boat green blue
 *   "Dr. Mari insists that the boat was green, not blue"            ->  mari insists boat green blue
 *
 * The second contains the first, so it is caught.
 */
export function skeleton(s: string): string {
  return skeletonTokens(s).join(" ");
}

// Crude, deliberately. A real stemmer is a dependency and a behaviour change on
// every call; all this needs is to survive the inflections an imitator reaches for
// (insists / insisting / insisted).
function stem(w: string): string {
  if (w.length < 5) return w;
  return w.replace(/(ings?|edly|ed|es|s)$/, "") || w;
}

export function skeletonTokens(s: string): string[] {
  return (String(s ?? "").toLowerCase().match(/[\p{L}\p{N}]+/gu) ?? [])
    .filter((w) => !FUNCTION_WORDS.has(w))
    .map(stem)
    .filter(Boolean);
}

/**
 * Does `hay` contain `needle`'s content words, IN ORDER, allowing gaps?
 *
 * Substring matching lost to one inserted "that". Contiguous skeleton matching then
 * lost to "insisting" and to an inserted "rather". Order is the last thing an
 * imitation preserves and the first thing an unrelated sentence fails, so it is the
 * right amount of strictness: an ordered subsequence of >= 3 content stems is
 * evidence of copying; anything looser becomes a topic detector.
 */
export function containsInOrder(hay: string[], needle: string[]): boolean {
  if (needle.length < MIN_SKELETON_WORDS) return false;
  let i = 0;
  for (const w of hay) if (w === needle[i] && ++i === needle.length) return true;
  return false;
}

// Below this a skeleton is too generic to be evidence of anything.
const MIN_SKELETON_WORDS = 3;

/**
 * Does `text` echo any of `phrases`, by skeleton rather than by characters?
 *
 * EXPORTED SO THE BENCH SCORES WITH THIS EXACT FUNCTION. The prompt bench must
 * grade candidate arms against each arm's OWN examples, which PROMPT_EXAMPLE_ECHOES
 * does not contain — so without this it would need its own copy of the matcher, and
 * the pilot's copy was `motivation.includes(example)`. That substring referee
 * undercounts in precisely the direction the shipped guard already proved fatal:
 * it misses "insists THAT the boat was green". A referee weaker than the guard
 * reports a prompt as clean when production would reject its output.
 *
 * One instrument, shared. Any new scorer calls this or it does not ship.
 */
export function echoesPhrases(text: string, phrases: string[]): boolean {
  const m = skeletonTokens(text);
  if (m.length === 0) return false;
  return phrases.some((p) => containsInOrder(m, skeletonTokens(p)));
}

/** Is this motivation the prompt's own words rather than the chunk's? */
export function echoesAnExample(motivation: string): boolean {
  return echoesPhrases(motivation, PROMPT_EXAMPLE_ECHOES.map((ex) => ex.phrase));
}

/**
 * The ledger, for tooling. Exposed so scripts/bait-rot.mjs can ask the question no
 * test asked before: not "can the ledger arrest this example" (bait-warrant) but
 * "can the STORE now corroborate it", which is what silently voids a warrant.
 * Returns the probe in inspectable form; the caller does the corpus scan.
 */
export function listEchoEntries(): { phrase: string; probeAll?: string[]; probeSource?: string; current: boolean }[] {
  return PROMPT_EXAMPLE_ECHOES.map((e) => ({
    phrase: e.phrase,
    probeAll: e.probeAll,
    probeSource: e.probe?.source,
    current: e.current === true,
  }));
}

/**
 * Should this analysis be REJECTED as a prompt echo?
 *
 * THE ESCAPE HATCH, and it is not optional (TC). The guard as first shipped made
 * the store's most meaningful sentence permanently unrecordable: if the speaker
 * ever genuinely says those words again, the beat is nulled — a confession banned
 * from its own store by its own fame.
 *
 * The discriminator is the same one that identified the echoes in the first place,
 * inverted and moved to write time. Of 669 stored echoes, only 4 had source text
 * containing the fear; that ratio is exactly what separates "the model reached for
 * the prompt" from "the speaker said it".
 *
 * So: echo in the motivation AND the phrase present in the SOURCE TEXT means
 * CORROBORATED — keep it. Echo with no trace in the source means the model
 * supplied it — reject.
 *
 * Deliberately checks the source for the ECHOED PHRASE ITSELF, not for a topic.
 * A looser test ("does this chunk mention memory?") would re-open the hole for any
 * conversation on the subject, which is most of them in this store.
 */
export function rejectAsEcho(motivation: string, sourceText: string): boolean {
  const m = skeletonTokens(motivation);
  if (m.length === 0) return false;
  const hit = PROMPT_EXAMPLE_ECHOES.find((ex) => containsInOrder(m, skeletonTokens(ex.phrase)));
  if (!hit) return false;
  // Corroborated: the speaker actually said it. Keep the beat.
  //
  // probeAll requires EVERY word, and the words are corpus-absent by construction.
  // Voiding this warrant takes a conversation containing several terms the store has
  // never held — as against /\blocksmith\b/, which one ordinary noun retired inside a
  // week. Word-boundaried for the same reason the legacy probes are: /never real/
  // without \b also matches "never really", which is everywhere in this store.
  const src = (sourceText ?? "").toLowerCase().replace(/\s+/g, " ");

  // GENERATED BAIT HAS NO ESCAPE HATCH, and closing it is not a loss.
  //
  // The hatch exists so a real confession is not banned by its own fame — sound for a
  // sentence a person could plausibly say. probeAll words are chosen by anti-join
  // BECAUSE the corpus has never held them, so "the source contains them" cannot mean
  // "someone finally said it" with any useful probability; it means the bait leaked
  // into the conversation. That is precisely the sequence that killed the boat: it was
  // discussed in a chat, the discussion made its probe corroborable, and the hatch
  // then let ten echoes through on the character it was discussed with.
  //
  // The false-negative cost is a genuine beat about, say, a cooperage AND a millpond
  // sluice in one chunk. Against that: a warrant everyone trusts and nobody checks.
  // And the remedy when it does happen is rotation, which now costs seconds — see
  // bait-tripwire.ts, which logs the event so the rotation actually gets triggered.
  if (hit.probeAll) return true;

  const corroborated = hit.probe ? hit.probe.test(src) : src.includes(hit.phrase);
  return !corroborated;
}

// (The long-form subtext instruction retired with the vikj rewrite — CHALLENGER_SUBTEXT below.)

/**
 * Mari's thread prose (vikj, 08-06), corrected by her own cold-start finding. The
 * GOOD/BAD label illustrations were pulled with n9bv — "name the situation, not
 * the cast" states the constraint instead of demonstrating it, carries no phrase
 * for the model to copy, and needs no warrant because it ships no bait.
 */
const THREAD_RULE_WITH_LIST = `- thread: if this moment belongs to something ongoing, label it. Reuse a label from the "Active threads" list when one names the same situation. Write a new label only when nothing listed fits, and name the situation, not the cast. Omit the field if nothing ongoing is at stake here.`;

// The no-list variant still MINTS, and deleting it would sterilise thread creation:
// every chat starts with zero threads, so a prompt that only ever selects from a list
// could never grow the first one. What changes is the dead reference to a block the
// user prompt did not send.
const THREAD_RULE_NO_LIST = `- thread: if this moment belongs to something ongoing, name it. Nothing is being tracked in this conversation yet, so write a label for the situation itself, not the cast. Omit the field if nothing ongoing is at stake here.`;

/**
 * Substituted once, at the end of buildSystemPrompt, rather than threaded through
 * all ten prompt builders. Keeps the emotion prompts unaware of thread state — and
 * keeps this change to two lines in a file being rewritten tomorrow.
 */
function applyThreadRule(prompt: string, hasThreads: boolean): string {
  return prompt.replace(
    THREAD_RULE_SLOT,
    hasThreads ? THREAD_RULE_WITH_LIST : THREAD_RULE_NO_LIST,
  );
}

const THREAD_RULE_SLOT = "__THREAD_RULE__";

// (SHARED_RULES retired with the vikj rewrite; the template below is the whole prompt.)

const JSON_FORMAT_STANDARD = `{"motivation":"...","relational_dynamics":"...","outcome":"...","emotions":${EMOTIONS_FORMAT},"subtext":null,"salience":0.0,"subject":"...","thread":null}`;
const JSON_FORMAT_WITH_SUBPATTERN = `{"motivation":"...","relational_dynamics":"...","outcome":"...","subpattern":"...","emotions":${EMOTIONS_FORMAT},"subtext":null,"salience":0.0,"subject":"...","thread":null}`;

// ── The challenger template (vikj) ──────────────────────────────────────────
//
// The production rewrite, assembled from ruled parts: the s6cu champion's shape
// (SHORT + off-planet won the sealed bench), Mari's thread prose (the existing
// THREAD_RULE_* constants, cold-start fix included), the no_beat shape she ruled
// (taught here for the first time — the parser accepted it since 08-05 while the
// prompt kept saying "say so" with nowhere to say it), and the compressed subtext
// and subpattern blocks per the packet's budget. Everything the audit found
// validator-shaped is gone; §4 of PROMPT-REWRITE-PACKET.md lists what code
// guarantees so this prose doesn't have to.
//
// SHIPPED AS THE DEFAULT 2026-08-20, by the pre-registered bench (packet §7),
// no author's exemption: x-echo −11.7 pts vs champion, boilerplate −3.3,
// validity −1.7 (better, and the rule allowed zero worse). TC approved the text
// 2026-08-19; the constants keep their CHALLENGER_ birth names deliberately —
// they say which side of the sealed bench this text came from.

const CHALLENGER_FIELDS: Record<Emotion, [string, string, string]> = {
  fear:          ["What is this person afraid of? What threat is activating it?", "How is the fear shaping the relationship right now?", "What does this signal about what happens next?"],
  shame:         ["What belief about the self was triggered, and by what?", "Is shame causing hiding, self-attack, or a bid for reassurance?", "How will they behave next, toward themselves or others?"],
  hope:          ["What are they hoping for, and what makes it feel possible now?", "How is the hope changing what they risk saying?", "What does this suggest they will reach for next?"],
  desire:        ["What do they want, specifically, in this moment?", "How is the wanting being offered, hidden, or negotiated?", "What does this set up between them?"],
  relief:        ["What stopped being a threat, and how long had it been one?", "What does the relief let them do that they could not before?", "What changes now that the pressure is off?"],
  vulnerability: ["What did they expose that they could have kept back?", "What is the exposure asking of the other person?", "What becomes possible or risky after this?"],
  trust:         ["What are they trusting the other with, concretely?", "What did the other do to earn or test it?", "What does extending it commit them to?"],
  anger:         ["What was violated, and what is the anger protecting?", "Is the anger creating distance or demanding to be seen?", "Where does this leave them next?"],
  joy:           ["What is the joy actually about, in its particulars?", "How is it being shared, performed, or withheld?", "What does it make more likely between them?"],
  dysregulation: ["What is underneath the surface behaviour?", "How is it landing on the other person?", "What happens if it is not met?"],
};

const CHALLENGER_SUBTEXT = `- subtext: only if the chunk contains sexual or physically intimate content — name the emotional function of that content (trust-building, vulnerability, power exchange, comfort-seeking, avoidance). Otherwise omit it.`;

/**
 * THE SECOND ASK (5x5y). Appended to the user prompt on ONE retry, when the intimacy
 * detector says the chunk warrants a subtext and the first answer omitted it.
 *
 * It carries NO EXAMPLE, deliberately. The prompt law (pifl) is that examples are
 * gravitational mass regardless of sign, and this instruction fires precisely when
 * the model has already shown it has nothing to say — the moment it is most likely to
 * reach for the nearest available phrasing. An illustration here would be echoed
 * straight into the store, and it would be echoed into the one field we have no
 * historical baseline for.
 *
 * THE ESCAPE HATCH IS LOAD-BEARING, not politeness. Enforcement whose only accepted
 * answer is a filled field does not produce subtext, it produces INVENTED subtext —
 * which is epf4 again, in a field created to hold a judgement. So a second refusal is
 * an allowed outcome, and it is recorded rather than punished. What we are buying is
 * a rate we can read, not a field that is never empty.
 */
const SUBTEXT_RETRY = `
The chunk you just analyzed contains physically intimate content, and your answer omitted the subtext field.

Answer again in the same JSON shape, and this time include subtext: name what the physical content is doing emotionally for these two people in THIS moment — what it builds, tests, asks for, or avoids.

If the chunk genuinely does not show you that, omit the field again. Do not fill it with something plausible.`;

/** Exposed for the prompt catalogue — every prompt this system sends must be readable. */
export function subtextRetryInstruction(): string {
  return SUBTEXT_RETRY.trim();
}

// The nine keys VERBATIM from the taxonomy the parser documents — the draft doc's
// first revision listed five keys that do not exist, from memory, and was caught
// by reading this file. Schema-from-memory is the exact failure the packet warns
// about; the compressed list must never drift from dysregulationPrompt's.
const CHALLENGER_SUBPATTERN = `- subpattern: which structural pattern fits best — bpd_testing, anxious_protest, avoidant_withdrawal, dissociation, catastrophizing, idealization, devaluation, emotional_flooding, or shutdown. Pick one key exactly as written, or omit the field.`;

function challengerPrompt(emotion: Emotion, structuralSubpatterns: string[]): string {
  const [m, r, o] = CHALLENGER_FIELDS[emotion];
  const dysreg = emotion === "dysregulation";
  const structuralHint = dysreg && structuralSubpatterns.length > 0
    ? `\nThe classifier also detected these structural signals in the text: ${structuralSubpatterns.join(", ")}. Weight these in your subpattern assessment.`
    : "";

  return `You are analyzing a moment of ${emotion.toUpperCase()} in a conversation.
${structuralHint}
- motivation: ${m}
- relational_dynamics: ${r}
- outcome: ${o}
${dysreg ? CHALLENGER_SUBPATTERN + "\n" : ""}${CHALLENGER_SUBTEXT}

- motivation must name the SPECIFIC content of THIS moment — what was actually said, feared, wanted, or done — so two different moments can never produce the same sentence. Genre descriptions are forbidden.
  TOO VAGUE, because it could describe a hundred different moments:
    ${BAIT.vague.map((e) => `"${e.text}"`).join(" / ")}
  SPECIFIC ENOUGH, because only one moment could have produced it:
${BAIT.specific.map((e) => `    "${e.text}"`).join("\n")}
  These are ILLUSTRATIONS OF SHAPE from an unrelated conversation. Never reuse their words.
- If you cannot name what happened in THIS chunk that specifically, there is no beat: reply {"no_beat": true} instead of reaching for a remembered phrase.
- subject: the single name of the person this beat is ABOUT — whose inner state does the chunk reveal? Attribute the beat to the character whose emotion it is, not the speaker label. Use a name from the "Known characters" list when you are given one, or "user" for the human player.
${THREAD_RULE_SLOT}

Reply with only this JSON:
${dysreg ? JSON_FORMAT_WITH_SUBPATTERN : JSON_FORMAT_STANDARD}`;
}

// ── Prompt dispatcher ──────────────────────────────────────────────────────

/**
 * The vikj rewrite IS the production prompt as of 2026-08-20. The sealed
 * challenger bench shipped it: x-echo 0% vs champion 12%, boilerplate 0% vs 3%,
 * validity BETTER (0% vs 2% invalid), n=60/arm, quarantined, echoesPhrases as
 * referee, verdict applied mechanically by prompt-bench-v2.mjs --v3. The 878/1246
 * token predecessors are deleted, not parked — a dead template in this file is a
 * drift surface; git history keeps the text.
 *
 * @param hasThreads whether the USER prompt will carry an "Active threads" block —
 *   selects Mari's WITH_LIST/NO_LIST thread rule (the cold-start fix).
 */
export function buildSystemPrompt(
  emotion: Emotion,
  structuralSubpatterns: string[],
  hasThreads = true,
): string {
  return applyThreadRule(challengerPrompt(emotion, structuralSubpatterns), hasThreads);
}

// ── Context window ─────────────────────────────────────────────────────────

export interface AnalysisContext {
  before?: ClassificationResult;
  after?: ClassificationResult;
}

// Prompt context beyond the chunk itself: who is in the scene, which threads
// are live, and what the scene is called (often the right new-thread label).
export interface AnalysisExtras {
  roster?: string[];
  threads?: string[];
  sceneTitle?: string;
  /** Only used to attribute a contamination event to a conversation. */
  chatId?: string;
}

function buildUserPrompt(result: ClassificationResult, context?: AnalysisContext, extras?: AnalysisExtras): string {
  const { chunk, scores, primaryEmotion, salience, structuralMatches } = result;
  const { roster, threads, sceneTitle } = extras ?? {};

  const rosterBlock = roster && roster.length > 0
    ? `Known characters (for the subject field): ${roster.join(", ")} — or "user" for the human player.\n\n`
    : "";

  const sceneLine = sceneTitle?.trim()
    // oknn: the caller now suppresses a title that names a person, so anything
    // reaching here describes a scene. The "never a person" clause stays as the
    // backstop — this line and the "never name the participants" rule above used
    // to contradict each other whenever the chat kept its default name, and the
    // later, more specific instruction won.
    ? `Scene name: "${sceneTitle.trim()}" — this names the SCENE, not a person. When a beat starts a NEW thread and this describes what is happening, prefer it as the thread label. If it is somebody's name, ignore it entirely and label the EVENT instead.\n\n`
    : "";

  const threadsBlock = threads && threads.length > 0
    ? `Active threads (for the thread field): ${threads.map((t) => `"${t}"`).join(", ")}\n\n`
    : "";

  const scoreLines = Object.entries(scores)
    .sort(([, a], [, b]) => b - a)
    .map(([e, s]) => `  ${e}: ${s.toFixed(2)}`)
    .join("\n");

  const structuralLines = structuralMatches.length > 0
    ? `\nStructural signals detected: ${structuralMatches.map(m => m.patternId).join(", ")}`
    : "";

  const beforeBlock = context?.before
    ? `Preceding context (${context.before.chunk.speaker} — for tone/intent reference only):
"""
${context.before.chunk.text.slice(0, 400)}${context.before.chunk.text.length > 400 ? "…" : ""}
"""

`
    : "";

  const afterBlock = context?.after
    ? `
Following context (${context.after.chunk.speaker} — for tone/intent reference only):
"""
${context.after.chunk.text.slice(0, 400)}${context.after.chunk.text.length > 400 ? "…" : ""}
"""`
    : "";

  return `${rosterBlock}${sceneLine}${threadsBlock}${beforeBlock}ANALYZE THIS — Speaker: ${chunk.speaker}
Primary emotion detected: ${primaryEmotion ?? "unknown"} (salience ${salience.toFixed(2)})
All emotion scores:
${scoreLines}${structuralLines}

Dialogue chunk:
"""
${chunk.text}
"""
${afterBlock}

Analyze the emotional beat in the chunk marked "ANALYZE THIS".`;
}

// ── Public API ─────────────────────────────────────────────────────────────

export async function analyzeChunk(
  result: ClassificationResult,
  context?: AnalysisContext,
  extras?: AnalysisExtras,
): Promise<BeatAnalysis | null> {
  if (!result.passesThreshold || !result.primaryEmotion) return null;

  const structuralSubpatterns = result.structuralMatches
    .map((m) => m.subpattern)
    .filter((s): s is string => Boolean(s));

  // The user prompt only carries an "Active threads" block when this is non-empty
  // (buildUserPrompt), so the system rule that cites that list is only reachable
  // under the same condition.
  const hasThreads = (extras?.threads?.length ?? 0) > 0;
  const systemPrompt = buildSystemPrompt(result.primaryEmotion, structuralSubpatterns, hasThreads);
  const userPrompt   = buildUserPrompt(result, context, extras);

  const raw = await callLlm(systemPrompt, userPrompt);
  const sourceText = result.chunk?.text ?? "";

  // TRIPWIRE. Fires on the SOURCE, not on the model's answer, because the leak event
  // is "bait vocabulary appeared in a chat" — which is upstream of, and independent
  // of, whether the model happened to echo it this time. Catching it here is what
  // makes rotation possible BEFORE the store absorbs a run of echoes, instead of
  // after, which is all scripts/bait-rot.mjs can offer.
  const tripped = detectBaitContamination(sourceText, listEchoEntries());
  for (const t of tripped) {
    recordContamination(getDataDir(), {
      at: new Date().toISOString(),
      entry: t.entry,
      words: t.words,
      chatId: extras?.chatId,
      excerpt: excerptAround(sourceText, t.words[0] ?? ""),
    });
  }

  // The chunk the model was asked about — the corroboration evidence for the echo
  // guard. Without it the guard cannot tell a copied example from a real utterance.
  // The exemption list is loaded here (memoised) rather than threaded through every
  // caller, because a caller that forgets it would convict REAL names — see epf4.
  const exempt = await knownNames();
  const analysis = parseAnalysisJson(raw, sourceText, exempt, extras?.chatId);
  return enforceSubtext(analysis, sourceText, systemPrompt, userPrompt, exempt, extras?.chatId);
}

/**
 * PROMPT ASKS, CODE ENFORCES (5x5y).
 *
 * The subtext field has been requested since May and emitted on 0.7% of the chunks
 * that warrant one — 11 times in 1,574 — because nothing ever checked. An optional
 * field an 8b model may silently skip is an advisory instruction, and this project
 * has ruled that advisory guards do no work.
 *
 * One retry, never two: a model that has now declined twice is telling us something,
 * and a third ask is how you talk a model into inventing. The original analysis is
 * kept and only the subtext is GRAFTED on, because the first answer's motivation and
 * outcome were fine — the retry exists to fill one gap, not to re-litigate the beat.
 */
export async function enforceSubtext(
  analysis: BeatAnalysis | null,
  sourceText: string,
  systemPrompt: string,
  userPrompt: string,
  exempt: string[] | null,
  chatId?: string,
  // Test seam. Production passes nothing and gets the real model call; a test passes
  // a stub and can assert HOW MANY TIMES it was called, which is the property that
  // matters most here — "one retry, never two" is a rule about call count.
  call: (system: string, user: string) => Promise<string | null> = callLlm,
): Promise<BeatAnalysis | null> {
  if (!analysis) return analysis;
  const verdict = classifyIntimacy(sourceText);
  if (!verdict.intimate) return analysis;

  const markers = [...verdict.strong, ...verdict.weak].slice(0, 6);
  const log = (outcome: SubtextOutcome) => recordSubtext(getDataDir(), {
    at: new Date().toISOString(),
    outcome,
    markers,
    chatId,
    excerpt: sourceText.replace(/\s+/g, " ").slice(0, 160),
  });

  if (analysis.subtext) { log("first-try"); return analysis; }

  const retryRaw = await call(systemPrompt, `${userPrompt}\n${SUBTEXT_RETRY}`);
  const retry = parseAnalysisJson(retryRaw, sourceText, exempt, chatId);
  if (!retry) { log("retry-failed"); return analysis; }
  if (!retry.subtext) { log("declined"); return analysis; }

  log("after-retry");
  return { ...analysis, subtext: retry.subtext };
}

export interface AnalyzedBeat {
  result:   ClassificationResult;
  analysis: BeatAnalysis;
}

// `targets` are the chunks to analyze (passing + speaker-filtered). `allChunks`
// is the full ordered classification list used purely for context — so the
// "preceding/following" blocks shown to the model are the TRUE adjacent chunks
// in the conversation, not the nearest other high-salience beat (which could be
// many turns away). Defaults to `targets` if not supplied.
// `onItem` (optional) is called after each chunk is processed — current is the
// 1-based index, total the count being analyzed, and reason is set only when the
// chunk failed (used by the story-import progress reporter).
export async function analyzeChunks(
  targets: ClassificationResult[],
  allChunks?: ClassificationResult[],
  onItem?: (current: number, total: number, reason?: string) => void,
  signal?: AbortSignal,
  extras?: AnalysisExtras,
): Promise<AnalyzedBeat[]> {
  const context = allChunks ?? targets;
  const passing = targets.filter((r) => r.passesThreshold && r.primaryEmotion);
  const total = passing.length;
  const output: AnalyzedBeat[] = [];

  let i = 0;
  for (const result of passing) {
    if (signal?.aborted) break; // cancelled — stop analyzing, keep what we have
    i++;
    const idx = context.indexOf(result);
    try {
      const analysis = await analyzeChunk(result, idx === -1 ? undefined : {
        before: context[idx - 1],
        after:  context[idx + 1],
      }, extras);
      if (analysis) {
        output.push({ result, analysis });
        onItem?.(i, total);
      } else {
        onItem?.(i, total, "model returned no parseable analysis");
      }
    } catch (err) {
      onItem?.(i, total, err instanceof Error ? err.message : String(err));
    }
  }

  return output;
}
