// Marinara Extender
// Copyright (C) 2026 TC Lowe
// Licensed under AGPL-3.0-only. See LICENSE.

// Stage 2: Deep Sentiment Analysis
//
// For each ClassificationResult that passes the salience threshold, calls the
// local Ollama model with an emotion-specific system prompt to extract
// structured BeatAnalysis JSON. Falls back to the external API if Ollama is
// unavailable.
//
// Each emotion has its own system prompt tuned to ask the right questions.
// Dysregulation is the most complex: it identifies which sub-pattern is
// driving the behavior and focuses on what's underneath the surface behavior.
//
// Context window: each chunk is analyzed with the preceding and following
// chunks visible so the model understands tone-vs-intent and conversational
// register rather than reading lines in isolation.

import { existsSync, readFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { getCachedAuth } from "../auth-cache.js";
import { fetchWithBackoff } from "../http.js";
import { localUrl, localEnabled, localModel, externalUpstream, externalModel } from "../llm-config.js";
import type { BeatAnalysis, ClassificationResult, Emotion, EmotionWeight } from "./types.js";

// ── JSON extraction (handles markdown-fenced responses) ────────────────────

function parseEmotions(raw: unknown): EmotionWeight[] | undefined {
  if (!Array.isArray(raw) || raw.length === 0) return undefined;
  const result: EmotionWeight[] = [];
  for (const item of raw) {
    if (typeof item === "object" && item !== null &&
        typeof (item as Record<string, unknown>).emotion === "string" &&
        typeof (item as Record<string, unknown>).weight === "number") {
      result.push({
        emotion: (item as { emotion: Emotion; weight: number }).emotion,
        weight:  (item as { emotion: Emotion; weight: number }).weight,
      });
    }
  }
  return result.length > 0 ? result : undefined;
}

/** The candidate JSON strings in a raw reply: the bare text, then a fenced block. */
function jsonAttempts(raw: string): string[] {
  return [
    String(raw ?? "").trim(),
    String(raw ?? "").match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1]?.trim() ?? "",
  ];
}

/**
 * Did the model legally DECLINE, as opposed to producing unparseable output?
 *
 * EXPORTED BECAUSE THE DISTINCTION DECIDES A PRE-REGISTERED TEST. Both outcomes
 * yield no beat, so the pipeline does not care — but "JSON validity must not drop a
 * point" is a ship condition for the prompt rewrite (vikj), and a prompt that
 * declines correctly would be scored as invalid JSON if declines and failures were
 * indistinguishable. That would penalise a draft for obeying its own instruction.
 *
 * Deliberately not logged per chunk: the analyzer avoids per-chunk output because it
 * breaks the import progress bar. Callers that want decline telemetry count it.
 */
export function isDeclineResponse(raw: string): boolean {
  for (const attempt of jsonAttempts(raw)) {
    if (!attempt) continue;
    try {
      const parsed = JSON.parse(attempt) as Record<string, unknown>;
      if (parsed.no_beat === true) return true;
    } catch { /* try next */ }
  }
  return false;
}

function parseAnalysisJson(raw: string, sourceText: string): BeatAnalysis | null {
  const attempts = jsonAttempts(raw);

  for (const attempt of attempts) {
    if (!attempt) continue;
    try {
      const parsed = JSON.parse(attempt) as Record<string, unknown>;

      // THE DECLINE PATH (vikj, Mari's ruling). Until this existed, the prompt told
      // the model "the chunk has no beat — say so rather than reaching for a
      // remembered phrase" and the schema gave it nowhere to say so. The only way
      // to comply was to emit malformed JSON, which made compliance indistinguishable
      // from failure — an advisory guard doing no work, the exact class ruled against
      // on 2026-08-04.
      //
      // The shape is `{"no_beat": true}`. `reason` is TOLERATED AND NEVER REQUIRED,
      // and that is deliberate: a mandatory freeform justification is a fresh
      // boilerplate surface bolted onto every decline, generated by a model that
      // copies whatever phrasing is nearest. Telemetry about declines belongs in
      // code, not in a field the model has to fill.
      //
      // Returns null, the same value a parse failure returns, because downstream
      // "no beat" is one outcome with one meaning. What changes is that a decline is
      // now a SUCCESSFUL parse — so it stops being counted as invalid JSON, and the
      // model has a legal way to obey the instruction.
      if (parsed.no_beat === true) return null;

      if (typeof parsed.motivation !== "string") continue;
      if (typeof parsed.relational_dynamics !== "string") continue;
      if (typeof parsed.outcome !== "string") continue;
      // pifl: the model copies the prompt's own example when it cannot be specific.
      // Measured before the fix: 792 beats (9% of the store) echoed one, 669 of them
      // the single sentence used to ILLUSTRATE "two different moments can never
      // produce the same sentence". Rewording the examples is necessary but is not a
      // guarantee — a model under-instructed by a long chunk reaches for whatever
      // phrasing is nearest, and the prompt is nearest. This is the guarantee.
      if (rejectAsEcho(parsed.motivation, sourceText)) return null;
      return {
        motivation:        parsed.motivation.trim(),
        relationalDynamics: parsed.relational_dynamics.trim(),
        outcome:           parsed.outcome.trim(),
        subpattern:        typeof parsed.subpattern === "string" ? parsed.subpattern : undefined,
        emotions:          parseEmotions(parsed.emotions),
        subtext:           typeof parsed.subtext === "string" && parsed.subtext.trim()
                             ? parsed.subtext.trim() : undefined,
        salience:          typeof parsed.salience === "number"
                             ? Math.min(1, Math.max(0, parsed.salience))
                             : 0.5,
        subject:           typeof parsed.subject === "string" && parsed.subject.trim()
                             ? parsed.subject.trim() : undefined,
        thread:            typeof parsed.thread === "string" && parsed.thread.trim()
                             ? parsed.thread.trim() : undefined,
      };
    } catch {
      // try next
    }
  }
  return null;
}

// ── Local model (Ollama or any OpenAI-compatible local server) ────────────

async function callLocal(systemPrompt: string, userPrompt: string): Promise<string | null> {
  if (!localEnabled()) return null;  // explicitly disabled — skip
  const base = localUrl();
  const model = localModel();

  try {
    const res = await fetch(`${base}/chat/completions`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user",   content: userPrompt },
        ],
        temperature: 0.2,
        stream: false,
        response_format: { type: "json_object" }, // force JSON; avoid prose fallback
      }),
      signal: AbortSignal.timeout(60_000),
    });
    if (!res.ok) return null;
    const json = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
    return json?.choices?.[0]?.message?.content ?? null;
  } catch {
    return null;
  }
}

// ── External API fallback ─────────────────────────────────────────────────

async function callExternal(systemPrompt: string, userPrompt: string): Promise<string> {
  const auth = getCachedAuth();
  if (!auth) {
    throw new Error(
      "Analyzer: local Ollama model unavailable and no API key set. Run Ollama (MARINARA_EXTENDER_LOCAL_URL/LOCAL_MODEL) or set MARINARA_EXTENDER_API_KEY.",
    );
  }
  const upstream = externalUpstream();
  const model = externalModel();

  const res = await fetchWithBackoff(`${upstream}/v1/chat/completions`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: auth },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user",   content: userPrompt },
      ],
      temperature: 0.2,
      max_tokens: 600,
    }),
  });
  if (!res.ok) throw new Error(`Analyzer external API failed (${res.status}): ${await res.text()}`);
  const json = (await res.json()) as { choices?: Array<{ message?: { content?: string } }> };
  return json?.choices?.[0]?.message?.content ?? "";
}

async function callLlm(systemPrompt: string, userPrompt: string): Promise<string> {
  const local = await callLocal(systemPrompt, userPrompt);
  if (local !== null) return local;
  // No per-chunk warn here — it would break the progress bar; the pipeline's
  // progress reporter surfaces per-chunk status instead.
  return callExternal(systemPrompt, userPrompt);
}

// ── System prompts ─────────────────────────────────────────────────────────
// Each prompt is tuned to extract the most meaningful signal for that emotion.
// All prompts request a compound emotions array and an optional subtext field.

const EMOTIONS_FORMAT = `[{"emotion":"<primary>","weight":0.0},{"emotion":"<secondary>","weight":0.0}]`;

// ── Example echo guard (pifl) ────────────────────────────────────────────────
// Every phrase the prompt puts in front of the model as an illustration, good or
// bad. A motivation matching one is not an analysis of the chunk; it is the model
// returning what it was shown.
//
// THE LIST MUST INCLUDE THE RETIRED EXAMPLES, not just the current ones. The old
// wording is what 669 stored beats echo, so a store that is still being written to
// by an older build — or re-analysed — has to keep being caught. Deleting a line
// from here silently re-opens the hole it was closing.
// `probe` is what CORROBORATION looks for in the source text, and it is not the
// phrase itself. A real utterance is first person and differently worded — "i'm
// afraid the memory loss means i was never real" — so requiring the motivation's
// exact third-person phrasing would corroborate nothing and ban the sentence
// anyway. The probe is the distinctive core that survives rephrasing.
//
// Word boundaries matter here: /never real/ without \b also matches "never
// really", which is ordinary English and appears all over this store. That exact
// slip produced false hits during the investigation.
//
// Where a phrase is generic ("exposes her personal fear"), there is no meaningful
// core to probe for, so no probe is given and corroboration requires the literal
// phrase — which is the right bar for a sentence nobody actually says.
//
// `probeAll` IS THE ROT-RESISTANT FORM, AND IT REPLACES `probe` FOR NEW BAIT.
// A single-word probe is a warrant one ordinary noun can void. /\blocksmith\b/ was
// voided within a week — "locksmith" became a live thread label via an unrelated
// metaphor about sealed read paths — and the failure is structural, not unlucky:
// bait is MOST likely to be parroted on chunks about its own topic, which are
// exactly the chunks where the hatch opens. Guard strength was inversely correlated
// with risk. probeAll requires EVERY listed word in the source, and the words are
// chosen by anti-join against the whole corpus (scripts/bait-select.mjs), so voiding
// one takes a conversation that contains several words the store has never held.
export interface EchoEntry {
  phrase: string;
  /** Legacy single-pattern corroboration. Rot-prone; kept for the retired entries. */
  probe?: RegExp;
  /** Corroborated only if EVERY word appears in the source text. */
  probeAll?: string[];
}

const PROMPT_EXAMPLE_ECHOES: EchoEntry[] = [
  // retired 2026-08-04, but the cause of the entire finding
  { phrase: "admits she's afraid the memory loss means she was never real", probe: /\bnever real\b/ },
  { phrase: "asks thomas to stay through the night for the first time", probe: /\bstay through the night\b/ },
  // current illustrations
  { phrase: "insists the boat was green, not blue, and will not let it go", probe: /\bgreen,? not blue\b/ },
  { phrase: "asks whether the locksmith ever called back", probe: /\blocksmith\b/ },
  // the "too vague" side — the model copies these too (measured: 107 beats opened
  // with a paraphrase of the first one)
  { phrase: "exposes her personal fear" },
  { phrase: "reveals her vulnerability and desire for connection" },
  { phrase: "the speaker is exposing their openness" },
  ...loadBaitFixture(),
];

/**
 * The current illustrations, loaded from a fixture rather than written here.
 *
 * SINGLE-CHANNEL EXPOSURE (TC, 2026-08-06). Bait may appear in the system prompt and
 * in NO other artifact this pipeline can ingest. The boat example rotted because it
 * was discussed in a chat that the sidecar then chunked, analysed and stored: ten
 * live motivations, several verbatim with a character name attached, two of them
 * dated after the bait shipped. One had even absorbed the meta-conversation
 * ("...which is deliberately absurd for this domain"). Discussing bait contaminates
 * bait, so the strings live in a file that only code reads, chosen by anti-join
 * against the whole corpus — see scripts/bait-select.mjs.
 *
 * THROWS rather than defaulting to empty. A missing fixture means every current
 * illustration silently loses its warrant while the prompt keeps showing examples —
 * the exact shape of failure this guard exists to prevent, and it would look like
 * a clean run. An unloadable ledger is a build error, not a degraded mode.
 */
function loadBaitFixture(): EchoEntry[] {
  const here = dirname(fileURLToPath(import.meta.url));
  const tries = [join(here, "bait.json"), join(here, "../../src/sentiment/bait.json")];
  for (const p of tries) {
    if (!existsSync(p)) continue;
    const raw = JSON.parse(readFileSync(p, "utf8")) as {
      specific?: { text: string; probe: string[] }[];
      vague?: { text: string }[];
    };
    return [
      ...(raw.specific ?? []).map((e) => ({ phrase: e.text, probeAll: e.probe })),
      // Vague bait gets NO probe on purpose: there is no distinctive core to look
      // for, so corroboration requires the literal phrase — the right bar for a
      // sentence nobody actually says.
      ...(raw.vague ?? []).map((e) => ({ phrase: e.text })),
    ];
  }
  throw new Error(
    `bait fixture not found (looked in: ${tries.join(", ")}). ` +
    `Regenerate with: node scripts/bait-select.mjs --from <candidates.json> --pick specific:2,vague:2 --write src/sentiment/bait.json`,
  );
}

// Function words carry the grammar an imitator redresses freely. The SKELETON is
// what survives that: content words, in order, with the joints removed.
const FUNCTION_WORDS = new Set([
  "a", "an", "the", "that", "this", "these", "those", "and", "or", "but", "not", "no",
  "is", "was", "were", "are", "am", "be", "been", "being", "will", "would", "shall",
  "should", "can", "could", "may", "might", "must", "do", "does", "did", "done",
  "have", "has", "had", "to", "of", "in", "on", "at", "by", "for", "with", "from",
  "as", "it", "its", "he", "she", "they", "them", "his", "her", "their", "him",
  "i", "me", "my", "we", "us", "our", "you", "your", "s", "t", "up", "out", "so",
  "let", "go", "about", "into", "over", "than", "then", "there", "here", "if",
]);

/**
 * The imitable core of a phrase: content words, in order, joints stripped.
 *
 * WHY THIS AND NOT SUBSTRING MATCHING. The first guard compared strings and died on
 * a single inserted word: the prompt said "insists the boat was green", the model
 * wrote "insists THAT the boat was green", and the beat sailed through into
 * professor_mari's ledger 90 minutes after the guard shipped. A mimicry engine
 * reproduces SHAPE, not characters, so a character-level test was always going to
 * lose to ordinary grammatical dressing.
 *
 *   "insists the boat was green, not blue, and will not let it go"  ->  insists boat green blue
 *   "Dr. Mari insists that the boat was green, not blue"            ->  mari insists boat green blue
 *
 * The second contains the first, so it is caught.
 */
export function skeleton(s: string): string {
  return skeletonTokens(s).join(" ");
}

// Crude, deliberately. A real stemmer is a dependency and a behaviour change on
// every call; all this needs is to survive the inflections an imitator reaches for
// (insists / insisting / insisted).
function stem(w: string): string {
  if (w.length < 5) return w;
  return w.replace(/(ings?|edly|ed|es|s)$/, "") || w;
}

export function skeletonTokens(s: string): string[] {
  return (String(s ?? "").toLowerCase().match(/[\p{L}\p{N}]+/gu) ?? [])
    .filter((w) => !FUNCTION_WORDS.has(w))
    .map(stem)
    .filter(Boolean);
}

/**
 * Does `hay` contain `needle`'s content words, IN ORDER, allowing gaps?
 *
 * Substring matching lost to one inserted "that". Contiguous skeleton matching then
 * lost to "insisting" and to an inserted "rather". Order is the last thing an
 * imitation preserves and the first thing an unrelated sentence fails, so it is the
 * right amount of strictness: an ordered subsequence of >= 3 content stems is
 * evidence of copying; anything looser becomes a topic detector.
 */
export function containsInOrder(hay: string[], needle: string[]): boolean {
  if (needle.length < MIN_SKELETON_WORDS) return false;
  let i = 0;
  for (const w of hay) if (w === needle[i] && ++i === needle.length) return true;
  return false;
}

// Below this a skeleton is too generic to be evidence of anything.
const MIN_SKELETON_WORDS = 3;

/**
 * Does `text` echo any of `phrases`, by skeleton rather than by characters?
 *
 * EXPORTED SO THE BENCH SCORES WITH THIS EXACT FUNCTION. The prompt bench must
 * grade candidate arms against each arm's OWN examples, which PROMPT_EXAMPLE_ECHOES
 * does not contain — so without this it would need its own copy of the matcher, and
 * the pilot's copy was `motivation.includes(example)`. That substring referee
 * undercounts in precisely the direction the shipped guard already proved fatal:
 * it misses "insists THAT the boat was green". A referee weaker than the guard
 * reports a prompt as clean when production would reject its output.
 *
 * One instrument, shared. Any new scorer calls this or it does not ship.
 */
export function echoesPhrases(text: string, phrases: string[]): boolean {
  const m = skeletonTokens(text);
  if (m.length === 0) return false;
  return phrases.some((p) => containsInOrder(m, skeletonTokens(p)));
}

/** Is this motivation the prompt's own words rather than the chunk's? */
export function echoesAnExample(motivation: string): boolean {
  return echoesPhrases(motivation, PROMPT_EXAMPLE_ECHOES.map((ex) => ex.phrase));
}

/**
 * The ledger, for tooling. Exposed so scripts/bait-rot.mjs can ask the question no
 * test asked before: not "can the ledger arrest this example" (bait-warrant) but
 * "can the STORE now corroborate it", which is what silently voids a warrant.
 * Returns the probe in inspectable form; the caller does the corpus scan.
 */
export function listEchoEntries(): { phrase: string; probeAll?: string[]; probeSource?: string }[] {
  return PROMPT_EXAMPLE_ECHOES.map((e) => ({
    phrase: e.phrase,
    probeAll: e.probeAll,
    probeSource: e.probe?.source,
  }));
}

/**
 * Should this analysis be REJECTED as a prompt echo?
 *
 * THE ESCAPE HATCH, and it is not optional (TC). The guard as first shipped made
 * the store's most meaningful sentence permanently unrecordable: if the speaker
 * ever genuinely says those words again, the beat is nulled — a confession banned
 * from its own store by its own fame.
 *
 * The discriminator is the same one that identified the echoes in the first place,
 * inverted and moved to write time. Of 669 stored echoes, only 4 had source text
 * containing the fear; that ratio is exactly what separates "the model reached for
 * the prompt" from "the speaker said it".
 *
 * So: echo in the motivation AND the phrase present in the SOURCE TEXT means
 * CORROBORATED — keep it. Echo with no trace in the source means the model
 * supplied it — reject.
 *
 * Deliberately checks the source for the ECHOED PHRASE ITSELF, not for a topic.
 * A looser test ("does this chunk mention memory?") would re-open the hole for any
 * conversation on the subject, which is most of them in this store.
 */
export function rejectAsEcho(motivation: string, sourceText: string): boolean {
  const m = skeletonTokens(motivation);
  if (m.length === 0) return false;
  const hit = PROMPT_EXAMPLE_ECHOES.find((ex) => containsInOrder(m, skeletonTokens(ex.phrase)));
  if (!hit) return false;
  // Corroborated: the speaker actually said it. Keep the beat.
  //
  // probeAll requires EVERY word, and the words are corpus-absent by construction.
  // Voiding this warrant takes a conversation containing several terms the store has
  // never held — as against /\blocksmith\b/, which one ordinary noun retired inside a
  // week. Word-boundaried for the same reason the legacy probes are: /never real/
  // without \b also matches "never really", which is everywhere in this store.
  const src = (sourceText ?? "").toLowerCase().replace(/\s+/g, " ");
  const corroborated = hit.probeAll
    ? hit.probeAll.every((w) => new RegExp(`\\b${w.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`, "i").test(src))
    : hit.probe ? hit.probe.test(src) : src.includes(hit.phrase);
  return !corroborated;
}

const SUBTEXT_INSTRUCTION = `
- subtext: If this chunk contains sexual or physically intimate content, analyze the EMOTIONAL FUNCTION of that content — what is it doing beyond arousal? Consider: trust-building, vulnerability, power exchange, marking/claiming, first-time significance, comfort-seeking, validation, grief, or avoidance. If no sexual/intimate content is present, omit this field or set it to null.`.trim();

/**
 * The thread rule, in two variants.
 *
 * CONDITIONAL BECAUSE A RULE WITH NO DATA POINTS AT A WALL (Mari's ruling, vikj):
 * when the user prompt carries no "Active threads" block, a rule instructing the
 * model to pick from that list is instructing it to read something absent.
 *
 * BUT THE RULE DOES TWO JOBS AND ONLY ONE OF THEM DIES. It (a) selects from the
 * live list and (b) MINTS a label when the moment starts something new. With no
 * active threads, (a) is dead and (b) is the only way a thread is ever created —
 * every chat starts with zero threads, so deleting the block outright would mean
 * no chat could ever grow its first one. So the no-threads variant drops the
 * selection clause and keeps the minting half.
 *
 * That is a DELETION of a dead reference, not new prose: the surviving sentences
 * are the shipped ones, unedited. Wording is Mari's jurisdiction; which of her
 * sentences are reachable is this file's.
 */
const THREAD_RULE_WITH_LIST = `- thread: which ongoing narrative thread this beat belongs to. Pick a label VERBATIM from the "Active threads" list when the beat continues one of them; if the moment clearly starts something new, give it a short 2–5 word label naming the EVENT or ARC. Never name the participants — the cast is not the story.
  GOOD: "Porsche test drive", "jurisprudence soft launch", "the Hargrove investigation"
  BAD: "thomas_and_mari" (cast list, not an event), "professor_mari_and_priya" (cast list, identifier style)
  Use null when the beat is incidental and belongs to no thread.`;

const THREAD_RULE_NO_LIST = `- thread: which ongoing narrative thread this beat belongs to. If the moment clearly starts something new, give it a short 2–5 word label naming the EVENT or ARC. Never name the participants — the cast is not the story.
  GOOD: "Porsche test drive", "jurisprudence soft launch", "the Hargrove investigation"
  BAD: "thomas_and_mari" (cast list, not an event), "professor_mari_and_priya" (cast list, identifier style)
  Use null when the beat is incidental and belongs to no thread.`;

/**
 * Substituted once, at the end of buildSystemPrompt, rather than threaded through
 * all ten prompt builders. Keeps the emotion prompts unaware of thread state — and
 * keeps this change to two lines in a file being rewritten tomorrow.
 */
function applyThreadRule(prompt: string, hasThreads: boolean): string {
  return prompt.replace(
    THREAD_RULE_SLOT,
    hasThreads ? THREAD_RULE_WITH_LIST : THREAD_RULE_NO_LIST,
  );
}

const THREAD_RULE_SLOT = "__THREAD_RULE__";

const SHARED_RULES = `
Rules:
- Analyze the chunk marked "ANALYZE THIS" only. Context blocks are provided so you understand conversational register and tone-vs-intent — a line that looks aggressive in isolation may be flirtatious in context, a line that sounds dismissive may be empathetic. Use context to correctly read intent.
- motivation must name the SPECIFIC content of THIS moment — what was actually said, feared, wanted, or done — so two different moments can never produce the same sentence. Genre descriptions are forbidden.
  TOO VAGUE, because it could describe a hundred different moments:
    "exposes her personal fear" / "reveals her vulnerability and desire for connection"
  SPECIFIC ENOUGH, because only one moment could have produced it:
    "insists the boat was green, not blue, and will not let it go"
    "asks whether the locksmith ever called back"
  These are ILLUSTRATIONS OF SHAPE from an unrelated conversation. Never reuse their
  words. If you cannot name what happened in THIS chunk that specifically, the chunk
  has no beat — say so rather than reaching for a remembered phrase.
- Be specific to the text provided — do not generalize.
- 1–3 sentences per field.
- salience: 0.0 = barely present, 1.0 = defining or pivotal moment.
- emotions: list the 1–3 emotions present, weighted by intensity (weights sum to ~1.0). First entry is the primary emotion.
- subject: the single name of the person this beat is ABOUT — whose inner emotional state does the chunk reveal? In roleplay one chunk often narrates several characters under one speaker label; attribute the beat to the character whose emotion it is, not the label. Use a name from the "Known characters" list when one is provided, or "user" when the beat belongs to the human player.
__THREAD_RULE__
- Respond with raw JSON only — no explanation, no markdown.`.trim();

const JSON_FORMAT_STANDARD = `{"motivation":"...","relational_dynamics":"...","outcome":"...","emotions":${EMOTIONS_FORMAT},"subtext":null,"salience":0.0,"subject":"...","thread":null}`;
const JSON_FORMAT_WITH_SUBPATTERN = `{"motivation":"...","relational_dynamics":"...","outcome":"...","subpattern":"...","emotions":${EMOTIONS_FORMAT},"subtext":null,"salience":0.0,"subject":"...","thread":null}`;

function fearPrompt(): string {
  return `You are analyzing a moment of fear in a conversation.

Extract the emotional beat as JSON:
- motivation: What is this person actually afraid of? What threat — real or perceived — is activating the fear response? What does this fear protect or preserve?
- relational_dynamics: How is the fear affecting or being shaped by the relationship in this moment? Does it push them toward clinging, fleeing, or freezing?
- outcome: What does this moment of fear signal about what could happen next — in this relationship or within this person?
${SUBTEXT_INSTRUCTION}

${SHARED_RULES}

Format: ${JSON_FORMAT_STANDARD}`;
}

function shamePrompt(): string {
  return `You are analyzing a moment of shame in a conversation.

Extract the emotional beat as JSON:
- motivation: What core belief about the self is being activated? What did this person do, feel, or reveal that triggered shame — and what does that say about their self-image?
- relational_dynamics: How is shame functioning relationally here? Is it causing hiding, withdrawal, self-attack, or a bid for reassurance?
- outcome: What does this shame moment suggest about how this person will behave next — toward themselves or toward others?
${SUBTEXT_INSTRUCTION}

${SHARED_RULES}

Format: ${JSON_FORMAT_STANDARD}`;
}

function hopePrompt(): string {
  return `You are analyzing a moment of hope in a conversation.

Extract the emotional beat as JSON:
- motivation: What is this person hoping for? What does this hope reveal about what they want or need most right now?
- relational_dynamics: How is hope functioning in the relationship — is it building trust, creating vulnerability, or setting up the risk of disappointment?
- outcome: What does this moment of hope suggest about where this person or relationship is heading?
${SUBTEXT_INSTRUCTION}

${SHARED_RULES}

Format: ${JSON_FORMAT_STANDARD}`;
}

function desirePrompt(): string {
  return `You are analyzing a moment of desire or longing in a conversation.

Extract the emotional beat as JSON:
- motivation: What does this person want — and what does that want reveal about what they feel is missing or possible? Is this desire for connection, safety, pleasure, or something else?
- relational_dynamics: How is desire functioning between these people — is it drawing them closer, creating tension, or exposing vulnerability?
- outcome: What does this desire moment suggest about what this person will do or feel next?
${SUBTEXT_INSTRUCTION}

${SHARED_RULES}

Format: ${JSON_FORMAT_STANDARD}`;
}

function reliefPrompt(): string {
  return `You are analyzing a moment of relief in a conversation.

Extract the emotional beat as JSON:
- motivation: What tension, fear, or dread has just released? What had this person been carrying that they can now put down?
- relational_dynamics: How does this relief affect the relationship dynamic — does it create closeness, lower defenses, or reveal how much pressure the person was under?
- outcome: What does this moment of relief open up — for this person or for this relationship?
${SUBTEXT_INSTRUCTION}

${SHARED_RULES}

Format: ${JSON_FORMAT_STANDARD}`;
}

function vulnerabilityPrompt(): string {
  // Measured failure mode (2026-06-13): this prompt produced identical
  // genre-boilerplate motivations for 37% of one character's vulnerability
  // beats (78 byte-identical strings) — an order of magnitude worse than any
  // other emotion. The WHAT-exactly demand below is targeted at that.
  return `You are analyzing a moment of vulnerability in a conversation.

Extract the emotional beat as JSON:
- motivation: WHAT EXACTLY is this person exposing — quote or closely paraphrase the specific admission, fear, or confession from the text. Never write "exposes her personal fear" or any sentence that could describe a different vulnerability moment; name THIS fear, THIS admission, THIS secret.
- relational_dynamics: How does this vulnerability land in the relationship? Does it invite reciprocity, create intimacy, or risk rejection?
- outcome: What does this moment of openness suggest about where this person or relationship could go from here?
${SUBTEXT_INSTRUCTION}

${SHARED_RULES}

Format: ${JSON_FORMAT_STANDARD}`;
}

function trustPrompt(): string {
  return `You are analyzing a moment involving trust or the breakdown of trust in a conversation.

Extract the emotional beat as JSON:
- motivation: Is trust being offered, tested, confirmed, or broken here? What does this person's relationship with trust reveal about their history or current state?
- relational_dynamics: How is trust functioning between these people — is it deepening the bond, revealing a wound, or exposing a pattern?
- outcome: What does this trust moment predict about what will happen next in this relationship?
${SUBTEXT_INSTRUCTION}

${SHARED_RULES}

Format: ${JSON_FORMAT_STANDARD}`;
}

function angerPrompt(): string {
  return `You are analyzing a moment of anger in a conversation.

Extract the emotional beat as JSON:
- motivation: What is underneath the anger? Anger is usually a secondary emotion — what hurt, fear, or violated need is it protecting? What does this person feel has been taken from them or disrespected?
- relational_dynamics: How is anger functioning between these people — is it creating distance, demanding to be seen, testing limits, or protecting something tender?
- outcome: What does this anger signal about what this person needs, and what might happen if they don't get it?
${SUBTEXT_INSTRUCTION}

${SHARED_RULES}

Format: ${JSON_FORMAT_STANDARD}`;
}

function joyPrompt(): string {
  return `You are analyzing a moment of joy, warmth, or happiness in a conversation.

Extract the emotional beat as JSON:
- motivation: What is generating this joy? What does it reveal about what this person values or has been missing?
- relational_dynamics: How is joy affecting the connection between these people — is it creating intimacy, softening tension, or marking a turning point?
- outcome: What does this moment of joy suggest about the relationship's potential or direction?
${SUBTEXT_INSTRUCTION}

${SHARED_RULES}

Format: ${JSON_FORMAT_STANDARD}`;
}

function dysregulationPrompt(structuralSubpatterns: string[]): string {
  const structuralHint = structuralSubpatterns.length > 0
    ? `\nThe classifier also detected these structural signals in the text: ${structuralSubpatterns.join(", ")}. Weight these in your subpattern assessment.\n`
    : "";

  return `You are analyzing a moment of emotional dysregulation — behavior driven by an unregulated emotional state rather than conscious choice. This applies to anyone in the conversation; dysregulation is not a character flaw, it is a signal of an unmet need.
${structuralHint}
Subpatterns to consider:
- bpd_testing: pushing someone away to test whether they will stay; creating conflict to check if the relationship is safe
- anxious_protest: escalating or intensifying behavior driven by fear of abandonment; reaching for connection through conflict
- avoidant_withdrawal: going cold, shutting down, creating distance when closeness feels dangerous or overwhelming
- dissociation: emotional flatness, one-word responses, grounding language ("ok.", "stay.", "here."), not being fully present
- catastrophizing: spiraling worst-case thinking; small events becoming proof of total disaster or permanent loss
- idealization: seeing someone as all-good, perfect, incapable of disappointing; unable to hold complexity
- devaluation: a sudden shift to seeing someone as all-bad, often following idealization
- emotional_flooding: overwhelm so intense that regulation is impossible; raw, unfiltered expression
- shutdown: complete withdrawal from the interaction; numbness, inability to continue engaging

Extract the emotional beat as JSON:
- motivation: What unmet need, fear, or wound is actually driving this behavior? Look beneath the surface action to what the person is really expressing or asking for.
- relational_dynamics: How is this dysregulation affecting the relationship dynamic right now? What is it asking of the other person?
- outcome: If this pattern continues unaddressed, what happens? What does this person actually need in this moment?
- subpattern: The single best-matching subpattern from the list above (exact key name), or null if none fits clearly.
${SUBTEXT_INSTRUCTION}

${SHARED_RULES}

Format: ${JSON_FORMAT_WITH_SUBPATTERN}`;
}

// ── Prompt dispatcher ──────────────────────────────────────────────────────

/**
 * @param hasThreads whether the USER prompt will carry an "Active threads" block.
 *   Defaults true, which is the pre-existing text — so the bench, the prompt dump
 *   and the bait-warrant test all keep seeing the full rule and nothing silently
 *   changes under them.
 */
export function buildSystemPrompt(
  emotion: Emotion,
  structuralSubpatterns: string[],
  hasThreads = true,
): string {
  const prompt = ((): string => {
    switch (emotion) {
      case "fear":          return fearPrompt();
      case "shame":         return shamePrompt();
      case "hope":          return hopePrompt();
      case "desire":        return desirePrompt();
      case "relief":        return reliefPrompt();
      case "vulnerability": return vulnerabilityPrompt();
      case "trust":         return trustPrompt();
      case "anger":         return angerPrompt();
      case "joy":           return joyPrompt();
      case "dysregulation": return dysregulationPrompt(structuralSubpatterns);
    }
  })();
  return applyThreadRule(prompt, hasThreads);
}

// ── Context window ─────────────────────────────────────────────────────────

export interface AnalysisContext {
  before?: ClassificationResult;
  after?: ClassificationResult;
}

// Prompt context beyond the chunk itself: who is in the scene, which threads
// are live, and what the scene is called (often the right new-thread label).
export interface AnalysisExtras {
  roster?: string[];
  threads?: string[];
  sceneTitle?: string;
}

function buildUserPrompt(result: ClassificationResult, context?: AnalysisContext, extras?: AnalysisExtras): string {
  const { chunk, scores, primaryEmotion, salience, structuralMatches } = result;
  const { roster, threads, sceneTitle } = extras ?? {};

  const rosterBlock = roster && roster.length > 0
    ? `Known characters (for the subject field): ${roster.join(", ")} — or "user" for the human player.\n\n`
    : "";

  const sceneLine = sceneTitle?.trim()
    // oknn: the caller now suppresses a title that names a person, so anything
    // reaching here describes a scene. The "never a person" clause stays as the
    // backstop — this line and the "never name the participants" rule above used
    // to contradict each other whenever the chat kept its default name, and the
    // later, more specific instruction won.
    ? `Scene name: "${sceneTitle.trim()}" — this names the SCENE, not a person. When a beat starts a NEW thread and this describes what is happening, prefer it as the thread label. If it is somebody's name, ignore it entirely and label the EVENT instead.\n\n`
    : "";

  const threadsBlock = threads && threads.length > 0
    ? `Active threads (for the thread field): ${threads.map((t) => `"${t}"`).join(", ")}\n\n`
    : "";

  const scoreLines = Object.entries(scores)
    .sort(([, a], [, b]) => b - a)
    .map(([e, s]) => `  ${e}: ${s.toFixed(2)}`)
    .join("\n");

  const structuralLines = structuralMatches.length > 0
    ? `\nStructural signals detected: ${structuralMatches.map(m => m.patternId).join(", ")}`
    : "";

  const beforeBlock = context?.before
    ? `Preceding context (${context.before.chunk.speaker} — for tone/intent reference only):
"""
${context.before.chunk.text.slice(0, 400)}${context.before.chunk.text.length > 400 ? "…" : ""}
"""

`
    : "";

  const afterBlock = context?.after
    ? `
Following context (${context.after.chunk.speaker} — for tone/intent reference only):
"""
${context.after.chunk.text.slice(0, 400)}${context.after.chunk.text.length > 400 ? "…" : ""}
"""`
    : "";

  return `${rosterBlock}${sceneLine}${threadsBlock}${beforeBlock}ANALYZE THIS — Speaker: ${chunk.speaker}
Primary emotion detected: ${primaryEmotion ?? "unknown"} (salience ${salience.toFixed(2)})
All emotion scores:
${scoreLines}${structuralLines}

Dialogue chunk:
"""
${chunk.text}
"""
${afterBlock}

Analyze the emotional beat in the chunk marked "ANALYZE THIS".`;
}

// ── Public API ─────────────────────────────────────────────────────────────

export async function analyzeChunk(
  result: ClassificationResult,
  context?: AnalysisContext,
  extras?: AnalysisExtras,
): Promise<BeatAnalysis | null> {
  if (!result.passesThreshold || !result.primaryEmotion) return null;

  const structuralSubpatterns = result.structuralMatches
    .map((m) => m.subpattern)
    .filter((s): s is string => Boolean(s));

  // The user prompt only carries an "Active threads" block when this is non-empty
  // (buildUserPrompt), so the system rule that cites that list is only reachable
  // under the same condition.
  const hasThreads = (extras?.threads?.length ?? 0) > 0;
  const systemPrompt = buildSystemPrompt(result.primaryEmotion, structuralSubpatterns, hasThreads);
  const userPrompt   = buildUserPrompt(result, context, extras);

  const raw = await callLlm(systemPrompt, userPrompt);
  // The chunk the model was asked about — the corroboration evidence for the echo
  // guard. Without it the guard cannot tell a copied example from a real utterance.
  return parseAnalysisJson(raw, result.chunk?.text ?? "");
}

export interface AnalyzedBeat {
  result:   ClassificationResult;
  analysis: BeatAnalysis;
}

// `targets` are the chunks to analyze (passing + speaker-filtered). `allChunks`
// is the full ordered classification list used purely for context — so the
// "preceding/following" blocks shown to the model are the TRUE adjacent chunks
// in the conversation, not the nearest other high-salience beat (which could be
// many turns away). Defaults to `targets` if not supplied.
// `onItem` (optional) is called after each chunk is processed — current is the
// 1-based index, total the count being analyzed, and reason is set only when the
// chunk failed (used by the story-import progress reporter).
export async function analyzeChunks(
  targets: ClassificationResult[],
  allChunks?: ClassificationResult[],
  onItem?: (current: number, total: number, reason?: string) => void,
  signal?: AbortSignal,
  extras?: AnalysisExtras,
): Promise<AnalyzedBeat[]> {
  const context = allChunks ?? targets;
  const passing = targets.filter((r) => r.passesThreshold && r.primaryEmotion);
  const total = passing.length;
  const output: AnalyzedBeat[] = [];

  let i = 0;
  for (const result of passing) {
    if (signal?.aborted) break; // cancelled — stop analyzing, keep what we have
    i++;
    const idx = context.indexOf(result);
    try {
      const analysis = await analyzeChunk(result, idx === -1 ? undefined : {
        before: context[idx - 1],
        after:  context[idx + 1],
      }, extras);
      if (analysis) {
        output.push({ result, analysis });
        onItem?.(i, total);
      } else {
        onItem?.(i, total, "model returned no parseable analysis");
      }
    } catch (err) {
      onItem?.(i, total, err instanceof Error ? err.message : String(err));
    }
  }

  return output;
}
