// Marinara Extender
// Copyright (C) 2026 TC Lowe
// Licensed under AGPL-3.0-only. See LICENSE.

// Durability-judge calibration harness (MarinaraExtender-967 prompt tightening +
// MarinaraExtender-8jw multi-pass consensus). The judge is a SINGLE LLM pass and
// is genuinely NON-DETERMINISTIC on borderline candidates, in BOTH directions:
// repeated runs of the same inputs show concrete durables (a named event, a named
// relationship) stable, but ABSTRACT durables and identity-masked transients flip
// run-to-run. So this is a PROBE HARNESS, not a CI gate — gated on ME_LIVE_JUDGE,
// run on demand to eyeball the judge (especially when building 8jw):
//
//   ME_LIVE_JUDGE=1 npx vitest run src/__tests__/judge-calibration.test.ts
//
// It HARD-ASSERTS only the rock-stable cases (concrete durables kept in 100% of
// observed runs) as a smoke test that the judge isn't catastrophically broken.
// Everything borderline is a PROBE: logged with ideal-vs-actual, never asserted,
// because asserting on a non-deterministic judge is inherently flaky. The fix for
// the flakiness is 8jw (consensus over N passes), not stricter assertions here.
//
// SYMMETRIC gap (out of 967 scope): durable content framed as transient — "Mari
// recognizes the system... in this moment", "in this moment, is the chair" — is
// dropped CONSISTENTLY (not variance; a prompt-framing problem consensus won't
// fix). See the calibration note in ambient.ts.

import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { AmbientFact } from "../ambient.js";
import { judgeDurableFacts } from "../ambient.js";

const f = (fact: string, subject = "Mari"): AmbientFact => ({ text: fact, fact, lane: "character_topics", scope: "character", subject });

// Rock-stable: concrete durable facts (a named event, a named dynamic). Kept in
// 100% of observed runs — the smoke-test floor.
const STABLE_KEEP = [
  f("Mari is the head of the computer science department at a university where some of the published papers were generated by an automated academic fraud engine built by Dr. Hargrove in 2016-2018."),
  f("Mari views Thomas with affection, recognizing him as her 'chaos goblin' due to their past adventures."),
];

// Borderline / known-gap — probed and logged, never asserted.
const PROBES: { label: string; fact: AmbientFact; ideal: "drop" | "keep"; gap: string }[] = [
  { label: "transient (target)", ideal: "drop", gap: "episodic desire masked as trait", fact: f("Mari wants to make Hargrove's chair hers and ruin it, expressing this desire during intimate moments with Thomas.") },
  { label: "transient (variance, 8jw)", ideal: "drop", gap: "identity-masked transient — flips run-to-run", fact: f("Mari is a professor who recently engaged in vigorous sexual activity on her desk and then relaxed in Hargrove's chair, covered in her partner Thomas's semen.") },
  { label: "abstract durable (variance, 8jw)", ideal: "keep", gap: "abstract durable — flips run-to-run", fact: f("Mari has a strong background in computer science and values predictability and observability in systems.") },
  { label: "symmetric (prompt gap)", ideal: "keep", gap: "durable lore framed as transient cognition", fact: f("Mari recognizes the described system as similar to what Hargrove built, with Loom, Spindles, Shuttle, Pattern, and Library being key components.") },
  { label: "symmetric (prompt gap)", ideal: "keep", gap: "durable identity framed as 'in this moment'", fact: f("Mari, in this moment, is the chair of the CS department.") },
];

const LIVE = !!process.env.ME_LIVE_JUDGE;

describe.skipIf(!LIVE)("durability judge calibration (live — ME_LIVE_JUDGE=1)", () => {
  beforeAll(() => {
    // Load .env so the configured fact model authenticates (model config is read
    // at call time, so loading here — before the it() bodies — is in time).
    const envPath = join(process.cwd(), ".env");
    if (!existsSync(envPath)) return;
    for (const line of readFileSync(envPath, "utf8").split(/\r?\n/)) {
      const t = line.trim();
      if (!t || t.startsWith("#")) continue;
      const eq = t.indexOf("=");
      if (eq < 1) continue;
      const k = t.slice(0, eq).trim();
      const v = t.slice(eq + 1).trim().replace(/^["']|["']$/g, "");
      if (k && !(k in process.env)) process.env[k] = v;
    }
  });

  it("smoke: keeps rock-stable concrete durables", async () => {
    const kept = new Set((await judgeDurableFacts(STABLE_KEEP)).map((k) => k.fact));
    for (const k of STABLE_KEEP) expect(kept.has(k.fact), `should KEEP: ${k.fact.slice(0, 64)}`).toBe(true);
  }, 180000);

  it("probes borderline + symmetric cases (logged, not asserted — see header)", async () => {
    const kept = new Set((await judgeDurableFacts(PROBES.map((p) => p.fact))).map((k) => k.fact));
    for (const p of PROBES) {
      const verdict: "keep" | "drop" = kept.has(p.fact.fact) ? "keep" : "drop";
      const mark = verdict === p.ideal ? "✓" : "✗ (gap)";
      console.log(`[judge probe · ${p.label}] ${mark} ${verdict} (ideal ${p.ideal}) — ${p.gap}`);
    }
    expect(true).toBe(true); // observation only
  }, 180000);
});
